CREATE OR REPLACE FUNCTION create_status_type() RETURNS void AS 'BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = ''sale_executive_status'') THEN CREATE TYPE sale_executive_status AS ENUM (''ACTIVE'', ''TERMINATED''); END IF; END;' LANGUAGE plpgsql; SELECT create_status_type(); DROP FUNCTION create_status_type();

CREATE TABLE IF NOT EXISTS tokens (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	token VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255),
    token BIGINT REFERENCES tokens (id)
);

CREATE TABLE IF NOT EXISTS sale_executives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255),
    phone_number VARCHAR(50),
    status sale_executive_status,
    token BIGINT REFERENCES tokens (id)
);

CREATE TABLE IF NOT EXISTS registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name VARCHAR(255),
    phone_number VARCHAR(50),
    registered_at TIMESTAMP,
    sale_executive_id BIGINT,
    FOREIGN KEY (sale_executive_id)
        REFERENCES sale_executives(id)
);